### ISSUE TITLE
"package github.com/fatih/color: cannot download, $GOPATH not set. For more details see: go help gopath" Error!

### ISSUE THREAD

**Issue by BaraSec** [EgeBalci/HERCULES#13]
Hi, I get this error after running the following command: "go get github.com/fatih/color"

The error is: "package github.com/fatih/color: cannot download, $GOPATH not set. For more details see: go help gopath".

How can I overcome this issue ?

Note: I didn't change the location of the HERCULES folder, just cloned it, accessed it and tried that command. I am using the very last updated kali linux 64-bit.

**Comment by EgeBalci** [comment]
Your golang environment is not setup, you need to set your GOPATH value in order to download golang packages thru git,  you can set it with `export GOPATH=$HOME`  this command sets your home folder as GOPATH, all go packages will be downloaded there, you can change $HOME with another path if you want.

Just after setting your GOPATH you can get the color package with `go get github.com/fatih/color`, when you get the color package run `go run Setup.go` command for installing HERCULES.
