### ISSUE TITLE
GO GET ERROR plz halp meh

### ISSUE THREAD

**Issue by johkeidude** [EgeBalci/HERCULES#14]
so duudee i have this GO problemo when i typo= go get github.com/fatih/color                              I get an error like deez= package github.com/fatih/color: cannot download, $GOPATH not set. For more details see: go help gopath

anddd when i try to run deez=go run Setup.go
I get an error like deez=Setup.go:6:8: cannot find package "github.com/fatih/color" in any of:
	/usr/lib/go-1.7/src/github.com/fatih/color (from $GOROOT)
	($GOPATH not set)

But keep dah good work and sorry for my bad london very bad london

**Comment by EgeBalci** [comment]
Your golang environment is not set, in order to download golang packages you need to set your GOPATH environment value, you can set it with this command `export GOPATH$HOME` this will set your GOPATH to your home directory it means all packages will be downloaded there, you can change the $HOME with a desired  path if you want.

After setting the GOPATH value  you can get the package with `go get github.com/fatih/color` then run the setup with `go run Setup.go` and you are good to go :)
